# This file configures GitHub repository settings for GitHub Pages
# See: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

name: GitHub Pages

on:
  # Run when needed, initial setup only
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
setup_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          # Configure GitHub Pages to use GitHub Actions
          source: 'gh-pages-branch'
