name: release
on:
  push:
  branches:
    - main

concurrency: ${{github.workflow}}-${{github.ref}}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - name: Get release info
        id: release
        run: |
          RELEASE_INFO=$(pnpm exec changeset status --output=json)
          echo "has_changes=$(echo $RELEASE_INFO | jq -r '.releases | length > 0')" >> $GITHUB_OUTPUT
          echo "$RELEASE_INFO" > .changeset-status.json

      - name: Build changed packages
        if: steps.release.outputs.has_changes == "true"
        run: pnpm build

      - name: Pull Request with version change
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: false
          commit: 'chore: version packages'
          title: 'chore: version packages'
          version: pnpm changeset version
          publish: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to npm registry
        if: steps.release.outputs.has_changes == "true"
        run: ts-node scripts/publish.s
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git Tag
        if: steps.release.outputs.has_changes == "true"
        run: |
          git config user.name "poornendushukla"
          git config user.email "shuklapoornendu@gmail.com"
          git tag -a "release-$(date +'%Y%m%d%H%M%S')" -m "Release $(date +'%Y-%m-%d %H:%M:%S')"
          git push --tags
