name: release
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

concurrency: ${{github.workflow}}-${{github.ref}}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - name: Build changed packages
        run: pnpm build

      - name: Config git user
        run: |
          git config user.name "poornendushukla"
          git config user.email "shuklapoornendu@gmail.com"

      - name: Create pull request with bumped version
        run: |
          git checkout -b version/version_bump
          git add .
          git commit -m "feat(release): Version update for the changed packages"
          git push
          gh pr create -B version/version_bump -H main --title 'feat(release): Version update for the changed packages' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        run: |
          git config user.name "poornendushukla"
          git config user.email "shuklapoornendu@gmail.com"
          git tag -a "release-$(date +'%Y%m%d%H%M%S')" -m "Release $(date +'%Y-%m-%d %H:%M:%S')"
          git push --tags
