name: release

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of app to release'
        required: true
        default: 'monkeyts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint check
        run: pnpm lint

  versioning:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run changeset versioning
        run: pnpm changeset version

  publish:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish package to NPM
        run: |
          pnpm publish --access public --no-git-checks --no-verify-registry --filter ${{ github.event.input.app_name }}

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
