name: release
on:
  push:
    branches:
      - main

concurrency: ${{github.workflow}}-${{github.ref}}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

permissions:
  contents: write
  pull-requests: write

jobs:
  versioning-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - name: Get changed packages
        id: changed
        run: |
          CHANGED_PACKAGES=$(pnpm exec changeset status --output=json | jq -r '.releases[].name' | tr '\n' ' ')
          echo "packages=$CHANGED_PACKAGES" >> $GITHUB_OUTPUT

      - name: Build changed packages
        run: pnpm build

      - name: Config git user
        run: |
          git config user.name "poornendushukla"
          git config user.email "shuklapoornendu@gmail.com"

      - name: Create versions or publish
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: false
          commit: 'chore: version packages'
          title: 'chore: version packages'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
